apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: zhaoqin/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        -
          name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: hello-world
---
